modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "${mod_github}/issues"
license = "${mod_license}"

[[mods]]
modId = "exposure"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.exposure]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.exposure]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.exposure]]
modId="jei"
mandatory=false
versionRange="[11.6.0.0,)"
ordering="NONE"
side="CLIENT"